# Nome do seu workflow
name: CI/CD - Build e Deploy do Portfólio

# Gatilho: Roda em push na branch 'main'
on:
  push:
    branches: [ "main" ]

# Tarefas a serem executadas
jobs:
  # Tarefa 1: Construir e enviar a imagem para o Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-web:latest

  # Tarefa 2: Fazer o deploy no servidor
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Executar comandos de deploy no servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # -> A chave é passada diretamente aqui
          script: |
            # Login no Docker Hub dentro do servidor
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            
            # Puxa a imagem mais recente do Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-web:latest
            
            # Para e remove o container antigo, se ele existir
            docker stop portfolio || true
            docker rm portfolio || true
            
            # Roda o novo container com a imagem atualizada
            docker run -d -p 80:3000 --name portfolio ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-web:latest
